Repository mcddhub/mcdd-spring-boot-study, pull requests merged in 2024-09, with the labels that each got.

#3 :sparkles: feat(): add common module
  common/pom.xml
  common/src/main/java/com/mcddhub/common/entity/BaseData.java
  common/src/main/java/com/mcddhub/common/entity/RestBean.java
  common/src/main/java/com/mcddhub/common/utils/Const.java
  common/src/main/java/com/mcddhub/common/utils/SnowflakeIdGenerator.java
  pom.xml
Labels: enhancement, major

#4 :bug: fix(): maven name error
  pom.xml
Labels: bug, patch

#6 :sparkles: feat(): template01-init module
  pom.xml
  template01-init/pom.xml
  template01-init/src/main/java/com/mcddhub/template01/Template01Application.java
  template01-init/src/main/resources/application-dev.yaml
  template01-init/src/main/resources/application-prod.yaml
  template01-init/src/main/resources/application.yaml
  template01-init/src/test/java/jzxy/mcdd/template01/Template01ApplicationTest.java
Labels: minor

#8 [Bug]: Sponsor and code style error #7
  .github/FUNDING.yaml
  .github/workflows/release-drafter.yml
  common/src/main/java/com/mcddhub/common/entity/BaseData.java
  common/src/main/java/com/mcddhub/common/entity/RestBean.java
  common/src/main/java/com/mcddhub/common/utils/Const.java
  common/src/main/java/com/mcddhub/common/utils/SnowflakeIdGenerator.java
  pom.xml
  template01-init/pom.xml
  template01-init/src/main/java/com/mcddhub/template01/Template01Application.java
  template01-init/src/main/resources/application-dev.yaml
  template01-init/src/main/resources/application-prod.yaml
  template01-init/src/main/resources/application.yaml
  template01-init/src/test/java/jzxy/mcdd/template01/Template01ApplicationTest.java
Labels: patch

#9 code style error
  .github/FUNDING.yaml
  .github/workflows/release-drafter.yml
  common/src/main/java/com/mcddhub/common/entity/BaseData.java
  common/src/main/java/com/mcddhub/common/entity/RestBean.java
  common/src/main/java/com/mcddhub/common/utils/Const.java
  common/src/main/java/com/mcddhub/common/utils/SnowflakeIdGenerator.java
Labels: patch

#12 Feat 10
  demo01-quickstart/pom.xml
  demo01-quickstart/src/main/java/com/mcddhub/demo01/Demo01Application.java
  demo01-quickstart/src/main/java/com/mcddhub/demo01/controller/MCDDController.java
  demo01-quickstart/src/main/java/com/mcddhub/demo01/controller/TestController.java
  demo01-quickstart/src/main/java/com/mcddhub/demo01/entity/MCDD.java
  demo01-quickstart/src/main/java/com/mcddhub/demo01/entity/MCDDSeries.java
  demo01-quickstart/src/main/resources/application-dev.yaml
  demo01-quickstart/src/main/resources/application-prod.yaml
  demo01-quickstart/src/main/resources/application.yaml
  demo01-quickstart/src/test/java/jzxy/mcdd/template01/Demo01ApplicationTest.java
  docs/spring-boot01.md
  pom.xml
Labels: major

#14 add db module and docker compose file to auto deploy
  .env.example
  .gitignore
  db.d/init/01-init.sql
  demo01-quickstart/src/test/java/com/mcddhub/demo01/Demo01ApplicationTest.java
  demo02-mp-db/pom.xml
  demo02-mp-db/src/main/java/com/mcddhub/demo02/Demo02Application.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/controller/McddCommentsController.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/controller/McddController.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/controller/McddSeriesController.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/entity/Mcdd.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/entity/McddComments.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/entity/McddSeries.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/repository/McddCommentsMapper.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/repository/McddMapper.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/repository/McddSeriesMapper.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/service/McddCommentsService.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/service/McddSeriesService.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/service/McddService.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/service/impl/McddCommentsServiceImpl.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/service/impl/McddSeriesServiceImpl.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/service/impl/McddServiceImpl.java
  demo02-mp-db/src/main/resources/application-dev.yaml
  demo02-mp-db/src/main/resources/application-prod.yaml
  demo02-mp-db/src/main/resources/application.yaml
  demo02-mp-db/src/test/java/com/mcddhub/demo02/Demo02ApplicationTest.java
  docker-compose.yaml
  pom.xml
  template01-init/src/test/java/com/mcddhub/template01/Template01ApplicationTest.java
Labels: enhancement

#20 Dev v1.1.0
  .github/workflows/release-drafter.yml
  .gitignore
  common/src/main/java/com/mcddhub/common/entity/RestBean.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/controller/McddCommentsController.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/controller/McddController.java
  demo02-mp-db/src/main/java/com/mcddhub/demo02/controller/McddSeriesController.java
  docs/spring-boot02.md
  frontend/.eslintrc.cjs
  frontend/.npmrc
  frontend/.prettierrc.json
  frontend/auto-imports.d.ts
  frontend/components.d.ts
  frontend/index.html
  frontend/jsconfig.json
  frontend/package.json
  frontend/public/favicon.svg
  frontend/src/App.vue
  frontend/src/assets/base.css
  frontend/src/assets/css/element.less
  frontend/src/assets/logo.svg
  frontend/src/assets/main.css
  frontend/src/component/McddCard.vue
  frontend/src/component/TabItem.vue
  frontend/src/main.js
  frontend/src/net/index.js
  frontend/src/router/index.js
  frontend/src/views/IndexView.vue
  frontend/src/views/main/Manage.vue
  frontend/src/views/main/Show.vue
  frontend/vite.config.js
Labels: bug, docs, enhancement

#22 21 feature add the test module for project
  demo03-test/pom.xml
  demo03-test/src/main/java/com/mcddhub/demo03/Demo03Application.java
  demo03-test/src/main/java/com/mcddhub/demo03/customer/CreateCustomerRequest.java
  demo03-test/src/main/java/com/mcddhub/demo03/customer/Customer.java
  demo03-test/src/main/java/com/mcddhub/demo03/customer/CustomerController.java
  demo03-test/src/main/java/com/mcddhub/demo03/customer/CustomerRepository.java
  demo03-test/src/main/java/com/mcddhub/demo03/customer/CustomerService.java
  demo03-test/src/main/java/com/mcddhub/demo03/exception/ApiErrorResponse.java
  demo03-test/src/main/java/com/mcddhub/demo03/exception/CustomerEmailUnavailableException.java
  demo03-test/src/main/java/com/mcddhub/demo03/exception/CustomerNotFoundException.java
  demo03-test/src/main/java/com/mcddhub/demo03/exception/GlobalExceptionHandler.java
  demo03-test/src/main/resources/application-dev.yaml
  demo03-test/src/main/resources/application-prod.yaml
  demo03-test/src/main/resources/application.yaml
  demo03-test/src/main/resources/db/data.sql
  demo03-test/src/main/resources/db/schema.sql
  demo03-test/src/test/java/com/mcddhub/demo03/AbstractTestcontainersTest.java
  demo03-test/src/test/java/com/mcddhub/demo03/Demo03ApplicationTest.java
  demo03-test/src/test/java/com/mcddhub/demo03/customer/CustomerIntegrationTest.java
  demo03-test/src/test/java/com/mcddhub/demo03/customer/CustomerRepositoryTest.java
  demo03-test/src/test/java/com/mcddhub/demo03/customer/CustomerServiceTest.java
  pom.xml
Labels: enhancement
